version: "3.7"
services:
     rabbitmq:
      image: rabbitmq:3-management-alpine
      hostname: rabbitmq
      labels:
        NAME: "rabbitmq"
      ports:
        - "15672:15672"
        - "5672:5672"
     logger:
        image: "datalust/seq"
        volumes:
        - ./Logs:/data
        ports:
        - "5341:80"
        environment:
         ACCEPT_EULA: "Y"
     ocelot-api-gateway:
                build: 
                 context: ./OcelotGateway
                 dockerfile: Dockerfile
                container_name: ocelotgateway
                ports:
                    - "0.0.0.0:8082:80"
                depends_on:
                - user-service
     user-service:
                build:
                 context: ./UserService
                 dockerfile: Dockerfile
                container_name: userservice
                ports:
                    - "0.0.0.0:8081:80"
                depends_on:
                    - rabbitmq
                    - db
                    
     db:
         image: "mcr.microsoft.com/mssql/server"
         container_name: sqlserver
         volumes:
          - sqlvolume:/var/opt/mssql

         environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
         ports:
                - "0.0.0.0:1433:1433"

volumes:
    rabbitmq:
        driver: local
    sqlvolume: