version: "3.7"
services:
    docker-mysql:
        image: "mysql:latest"
        environment:
            - MYSQL_ROOT_PASSWORD=IQnJclrDZKJytgwX4txV
            - MYSQL_DATABASE=dbi407741
            - MYSQL_PASSWORD=IQnJclrDZKJytgwX4txV
        

    user-service:
        image: kwetter_user-service:latest
        ports:
            - "22726:22726"
        build:
         context: ./UserService
         args:
          URL_PORT: 22726
        links:
            - docker-mysql
