name: Build the AuthenticationService

on:
  push:
    paths:
      - "AuthenticationService/**"
      - ".github/workflows/AuthenticationService.yml"

env:
  AUTH_PATH: 'AuthenticationService/AuthenticationService.csproj'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Change directory'
      run: cd AuthenticationService

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: 'Restory packages'
      run: dotnet restore ${{ env.AUTH_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.AUTH_PATH }} --no-restore --configuration Release