name: Build the OcelotGateway 

on:
  push:
    paths:
      - "OcelotGateway/**"
      - ".github/workflows/OcelotGateway.yml"

env:
  AUTH_PATH: 'OcelotGateway/OcelotGateway.csproj'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.AUTH_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.AUTH_PATH }} --no-restore --configuration Release
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: OcelotGateway
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/kwetter-ocelot-gateway:latest
